---
all:
  children:
    bc250_cluster:
      children:
        llama_coordinator:
          hosts:
            bowie:
              ansible_host: 192.0.2.170
        llama_rpc_workers:
          hosts:
            crockett:
              ansible_host: 192.0.2.171
    backend_bandwidth_server:
      hosts:
        crockett:
